version: '2'

services:
  prilphp:
    image:  pril_php:0.1
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html
    networks:
       default:
           aliases:
             - api.pril.local

  registralphp:
    image:  registral_php:0.1
    ports:
      - 81:80
    volumes:
      - /var/www/html:/var/www/html
    networks:
       default:
           aliases:
              - api.registral.local

  lugarphp:
    image:  lugar_php:0.1
    ports:
      - 82:80
    volumes:
      - /var/www/html:/var/www/html
    networks:
       default:
           aliases:
              - api.lugar.local
  mimysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
     - /dbdata:/var/lib/mysql
