<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "accion".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $fecha
 * @property integer $tipo_accionid
 * @property integer $area_entrenamientoid
 *
 * @property \app\models\AreaEntrenamiento $areaEntrenamiento
 * @property \app\models\TipoAccion $tipoAccion
 * @property \app\models\Informe[] $informes
 * @property string $aliasModel
 */
abstract class Accion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'accion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'tipo_accionid', 'area_entrenamientoid'], 'required'],
            [['fecha'], 'safe'],
            [['tipo_accionid', 'area_entrenamientoid'], 'integer'],
            [['nombre'], 'string', 'max' => 200],
            [['area_entrenamientoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AreaEntrenamiento::className(), 'targetAttribute' => ['area_entrenamientoid' => 'id']],
            [['tipo_accionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoAccion::className(), 'targetAttribute' => ['tipo_accionid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'fecha' => 'Fecha',
            'tipo_accionid' => 'Tipo Accionid',
            'area_entrenamientoid' => 'Area Entrenamientoid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreaEntrenamiento()
    {
        return $this->hasOne(\app\models\AreaEntrenamiento::className(), ['id' => 'area_entrenamientoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoAccion()
    {
        return $this->hasOne(\app\models\TipoAccion::className(), ['id' => 'tipo_accionid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInformes()
    {
        return $this->hasMany(\app\models\Informe::className(), ['accionid' => 'id']);
    }




}
