<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "area_entrenamiento".
 *
 * @property integer $id
 * @property string $tarea
 * @property integer $planid
 * @property integer $destinatarioid
 * @property string $fecha_inicial
 * @property string $fecha_final
 * @property string $descripcion_baja
 * @property integer $ofertaid
 * @property string $jornada
 * @property string $observacion
 *
 * @property \app\models\Accion[] $accions
 * @property \app\models\Destinatario $destinatario
 * @property \app\models\Oferta $oferta
 * @property \app\models\Plan $plan
 * @property string $aliasModel
 */
abstract class AreaEntrenamiento extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'area_entrenamiento';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tarea', 'planid', 'destinatarioid', 'ofertaid'], 'required'],
            [['planid', 'destinatarioid', 'ofertaid'], 'integer'],
            [['fecha_inicial', 'fecha_final'], 'safe'],
            [['descripcion_baja', 'jornada', 'observacion'], 'string'],
            [['tarea'], 'string', 'max' => 45],
            [['destinatarioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Destinatario::className(), 'targetAttribute' => ['destinatarioid' => 'id']],
            [['ofertaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Oferta::className(), 'targetAttribute' => ['ofertaid' => 'id']],
            [['planid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Plan::className(), 'targetAttribute' => ['planid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tarea' => 'Tarea',
            'planid' => 'Planid',
            'destinatarioid' => 'Destinatarioid',
            'fecha_inicial' => 'Fecha Inicial',
            'fecha_final' => 'Fecha Final',
            'descripcion_baja' => 'Descripcion Baja',
            'ofertaid' => 'Ofertaid',
            'jornada' => 'Jornada',
            'observacion' => 'Observacion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccions()
    {
        return $this->hasMany(\app\models\Accion::className(), ['area_entrenamientoid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDestinatario()
    {
        return $this->hasOne(\app\models\Destinatario::className(), ['id' => 'destinatarioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOferta()
    {
        return $this->hasOne(\app\models\Oferta::className(), ['id' => 'ofertaid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlan()
    {
        return $this->hasOne(\app\models\Plan::className(), ['id' => 'planid']);
    }




}
