<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "destinatario".
 *
 * @property integer $id
 * @property integer $oficioid
 * @property string $legajo
 * @property integer $calificacion
 * @property integer $profesionid
 * @property string $fecha_ingreso
 * @property string $origen
 * @property string $observacion
 * @property string $deseo_lugar_entrenamiento
 * @property string $deseo_actividad
 * @property string $fecha_presentacion
 * @property integer $personaid
 * @property string $banco_cbu
 * @property string $banco_nombre
 * @property string $banco_alias
 * @property integer $experiencia_laboral
 *
 * @property \app\models\AreaEntrenamiento[] $areaEntrenamientos
 * @property \app\models\Oficio $oficio
 * @property \app\models\Profesion $profesion
 * @property string $aliasModel
 */
abstract class Destinatario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'destinatario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['oficioid', 'calificacion', 'profesionid', 'personaid', 'experiencia_laboral'], 'integer'],
            [['legajo', 'fecha_ingreso', 'fecha_presentacion'], 'required'],
            [['fecha_ingreso', 'fecha_presentacion'], 'safe'],
            [['observacion', 'deseo_lugar_entrenamiento', 'deseo_actividad'], 'string'],
            [['legajo'], 'string', 'max' => 45],
            [['origen', 'banco_cbu', 'banco_nombre', 'banco_alias'], 'string', 'max' => 200],
            [['personaid'], 'unique'],
            [['oficioid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Oficio::className(), 'targetAttribute' => ['oficioid' => 'id']],
            [['profesionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Profesion::className(), 'targetAttribute' => ['profesionid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'oficioid' => 'Oficioid',
            'legajo' => 'Legajo',
            'calificacion' => 'Calificacion',
            'profesionid' => 'Profesionid',
            'fecha_ingreso' => 'Fecha Ingreso',
            'origen' => 'Origen',
            'observacion' => 'Observacion',
            'deseo_lugar_entrenamiento' => 'Deseo Lugar Entrenamiento',
            'deseo_actividad' => 'Deseo Actividad',
            'fecha_presentacion' => 'Fecha Presentacion',
            'personaid' => 'Personaid',
            'banco_cbu' => 'Banco Cbu',
            'banco_nombre' => 'Banco Nombre',
            'banco_alias' => 'Banco Alias',
            'experiencia_laboral' => 'Experiencia Laboral',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'personaid' => 'Este campo debe ser obligatorio, pero esto se debe obligar mediante una regla de negocio a mano, es decir con codigo puro',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreaEntrenamientos()
    {
        return $this->hasMany(\app\models\AreaEntrenamiento::className(), ['destinatarioid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOficio()
    {
        return $this->hasOne(\app\models\Oficio::className(), ['id' => 'oficioid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfesion()
    {
        return $this->hasOne(\app\models\Profesion::className(), ['id' => 'profesionid']);
    }




}
