<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "informe".
 *
 * @property integer $id
 * @property integer $accionid
 * @property string $detalle
 *
 * @property \app\models\Accion $accion
 * @property string $aliasModel
 */
abstract class Informe extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'informe';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['accionid'], 'required'],
            [['accionid'], 'integer'],
            [['detalle'], 'string'],
            [['accionid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Accion::className(), 'targetAttribute' => ['accionid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'accionid' => 'Accionid',
            'detalle' => 'Detalle',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccion()
    {
        return $this->hasOne(\app\models\Accion::className(), ['id' => 'accionid']);
    }




}
