<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "oferta".
 *
 * @property integer $id
 * @property integer $ambiente_trabajoid
 * @property string $nombre_sucursal
 * @property string $puesto
 * @property string $area
 * @property string $fecha_inicial
 * @property string $fecha_final
 * @property string $demanda_laboral
 * @property string $objetivo
 * @property integer $lugarid
 *
 * @property \app\models\AreaEntrenamiento[] $areaEntrenamientos
 * @property \app\models\AmbienteTrabajo $ambienteTrabajo
 * @property string $aliasModel
 */
abstract class Oferta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'oferta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ambiente_trabajoid', 'puesto', 'fecha_inicial', 'demanda_laboral', 'lugarid'], 'required'],
            [['ambiente_trabajoid', 'lugarid'], 'integer'],
            [['fecha_inicial', 'fecha_final'], 'safe'],
            [['demanda_laboral', 'objetivo'], 'string'],
            [['nombre_sucursal'], 'string', 'max' => 200],
            [['puesto', 'area'], 'string', 'max' => 300],
            [['ambiente_trabajoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\AmbienteTrabajo::className(), 'targetAttribute' => ['ambiente_trabajoid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ambiente_trabajoid' => 'Ambiente Trabajoid',
            'nombre_sucursal' => 'Nombre Sucursal',
            'puesto' => 'Puesto',
            'area' => 'Area',
            'fecha_inicial' => 'Fecha Inicial',
            'fecha_final' => 'Fecha Final',
            'demanda_laboral' => 'Demanda Laboral',
            'objetivo' => 'Objetivo',
            'lugarid' => 'Lugarid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreaEntrenamientos()
    {
        return $this->hasMany(\app\models\AreaEntrenamiento::className(), ['ofertaid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAmbienteTrabajo()
    {
        return $this->hasOne(\app\models\AmbienteTrabajo::className(), ['id' => 'ambiente_trabajoid']);
    }




}
