<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "plan".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $monto
 * @property string $hora_semanal
 *
 * @property \app\models\AreaEntrenamiento[] $areaEntrenamientos
 * @property string $aliasModel
 */
abstract class Plan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'monto', 'hora_semanal'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'monto' => 'Monto',
            'hora_semanal' => 'Hora Semanal',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreaEntrenamientos()
    {
        return $this->hasMany(\app\models\AreaEntrenamiento::className(), ['planid' => 'id']);
    }




}
