<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tipo_ambiente_trabajo".
 *
 * @property integer $id
 * @property string $nombre
 *
 * @property \app\models\AmbienteTrabajo[] $ambienteTrabajos
 * @property string $aliasModel
 */
abstract class TipoAmbienteTrabajo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tipo_ambiente_trabajo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAmbienteTrabajos()
    {
        return $this->hasMany(\app\models\AmbienteTrabajo::className(), ['tipo_ambiente_trabajoid' => 'id']);
    }




}
