-- MySQL Script generated by MySQL Workbench
-- vie 15 jun 2018 14:25:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pril
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pril` ;

-- -----------------------------------------------------
-- Schema pril
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pril` DEFAULT CHARACTER SET utf8 ;
USE `pril` ;

-- -----------------------------------------------------
-- Table `pril`.`destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `oficio` VARCHAR(200) NULL,
  `legajo` VARCHAR(45) NOT NULL,
  `calificacion` INT NULL,
  `profesion` VARCHAR(200) NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `origen` VARCHAR(200) NULL,
  `observacion` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`tipo_ambiente_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`tipo_ambiente_trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`ambiente_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`ambiente_trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `calificacion` INT NULL,
  `representanteid` INT NOT NULL,
  `legajo` VARCHAR(45) NULL,
  `observacion` TEXT NULL,
  `cuit` VARCHAR(45) NULL,
  `actividad` VARCHAR(200) NULL,
  `tipo_ambiente_trabajoid` INT NOT NULL,
  `lugarid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ambiente_trabajo_tipo_ambiente_trabajo_idx` (`tipo_ambiente_trabajoid` ASC),
  CONSTRAINT `fk_ambiente_trabajo_tipo_ambiente_trabajo`
    FOREIGN KEY (`tipo_ambiente_trabajoid`)
    REFERENCES `pril`.`tipo_ambiente_trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`oferta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ambiente_trabajoid` INT NOT NULL,
  `nombre_sucursal` VARCHAR(200) NULL,
  `puesto` VARCHAR(200) NOT NULL,
  `area` VARCHAR(200) NULL,
  `fecha_inicial` DATETIME NOT NULL,
  `fecha_final` DATETIME NULL,
  `demanda_laboral` TEXT NOT NULL,
  `objetivo` TEXT NULL,
  `dia_horario` VARCHAR(200) NULL,
  `lugarid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oferta_ambiente_trabajo1_idx` (`ambiente_trabajoid` ASC),
  CONSTRAINT `fk_oferta_ambiente_trabajo1`
    FOREIGN KEY (`ambiente_trabajoid`)
    REFERENCES `pril`.`ambiente_trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `monto` VARCHAR(45) NULL,
  `hora_semanal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`area_entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`area_entrenamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarea` VARCHAR(45) NOT NULL,
  `planid` INT NOT NULL,
  `destinatarioid` INT NOT NULL,
  `fecha_inicial` DATETIME NULL,
  `fecha_final` DATETIME NULL,
  `descripcion_baja` TEXT NULL,
  `ofertaid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_area_entrenamiento_plan1_idx` (`planid` ASC),
  INDEX `fk_area_entrenamiento_destinatario1_idx` (`destinatarioid` ASC),
  INDEX `fk_area_entrenamiento_oferta1_idx` (`ofertaid` ASC),
  CONSTRAINT `fk_area_entrenamiento_plan1`
    FOREIGN KEY (`planid`)
    REFERENCES `pril`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_entrenamiento_destinatario1`
    FOREIGN KEY (`destinatarioid`)
    REFERENCES `pril`.`destinatario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_entrenamiento_oferta1`
    FOREIGN KEY (`ofertaid`)
    REFERENCES `pril`.`oferta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`tipo_accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`tipo_accion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`accion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NULL,
  `tipo_accionid` INT NOT NULL,
  `area_entrenamientoid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accion_tipo_accion1_idx` (`tipo_accionid` ASC),
  INDEX `fk_accion_area_entrenamiento1_idx` (`area_entrenamientoid` ASC),
  CONSTRAINT `fk_accion_tipo_accion1`
    FOREIGN KEY (`tipo_accionid`)
    REFERENCES `pril`.`tipo_accion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accion_area_entrenamiento1`
    FOREIGN KEY (`area_entrenamientoid`)
    REFERENCES `pril`.`area_entrenamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pril`.`informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pril`.`informe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accionid` INT NOT NULL,
  `detalle` TEXT NULL,
  PRIMARY KEY (`id`, `accionid`),
  INDEX `fk_informe_accion1_idx` (`accionid` ASC),
  CONSTRAINT `fk_informe_accion1`
    FOREIGN KEY (`accionid`)
    REFERENCES `pril`.`accion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
