<?php

return [    
    "destinatario1" => [
        "id" => 1,
        "legajo" => 'usb123/6',
        "calificacion" => 1,
        "fecha_ingreso" => date("Y-m-d H:i:s"),
        "origen" => "un origen fixture",
        "observacion" => 1,
        "deseo_lugar_entrenamiento" => 1,
        "deseo_actividad" => 1,
        "fecha_presentacion" => '2010-10-10',
        "personaid" => 2,
        "banco_cbu" => 1,
        "banco_nombre" => 1,
        "banco_alias" => 1,
        "experiencia_laboral" => 1,
    ],
    "destinatario2" => [
        "id" => 2,
        "legajo" => 'usb123/7',
        "calificacion" => 1,
        "fecha_ingreso" => date("Y-m-d H:i:s"),
        "origen" => "un origen fixture",
        "observacion" => 1,
        "deseo_lugar_entrenamiento" => 1,
        "deseo_actividad" => 1,
        "fecha_presentacion" => '2010-10-10',
        "personaid" => 3,
        "banco_cbu" => 1,
        "banco_nombre" => 1,
        "banco_alias" => 1,
        "experiencia_laboral" => 1,
    ],
    "destinatario3" => [
        "id" => 3,
        "legajo" => 'usb123/8',
        "calificacion" => 1,
        "fecha_ingreso" => date("Y-m-d H:i:s"),
        "origen" => "un origen fixture",
        "observacion" => 1,
        "deseo_lugar_entrenamiento" => 1,
        "deseo_actividad" => 1,
        "fecha_presentacion" => '2010-10-10',
        "personaid" => 4,
        "banco_cbu" => 1,
        "banco_nombre" => 1,
        "banco_alias" => 1,
        "experiencia_laboral" => 1,
    ],
    "destinatario4" => [
        "id" => 4,
        "legajo" => 'usb123/9',
        "calificacion" => 1,
        "fecha_ingreso" => date("Y-m-d H:i:s"),
        "origen" => "un origen fixture",
        "observacion" => 1,
        "deseo_lugar_entrenamiento" => 1,
        "deseo_actividad" => 1,
        "fecha_presentacion" => '2010-10-10',
        "personaid" => 5,
        "banco_cbu" => 1,
        "banco_nombre" => 1,
        "banco_alias" => 1,
        "experiencia_laboral" => 1,
    ]
    
    
];
