<?php

return [    
    "oferta1" => [
        "id" => 1,
        "ambiente_trabajoid" => 1,
        "nombre_sucursal" => 'Sucursal Nº 1',
        "puesto" => "cajera",
        "area" => "",
        "fecha_inicial" => '2018-10-13 10:34:45',
        "fecha_final" => "",
        "demanda_laboral" => "falta una cajera",
        "objetivo" => "conseguir personal especificamente para la caja",
        "lugarid" => 1,
    ],
    "oferta2" => [
        "id" => 2,
        "ambiente_trabajoid" => 1,
        "nombre_sucursal" => 'Sucursal Nº 2',
        "puesto" => "cajera",
        "area" => "",
        "fecha_inicial" => '2018-09-10 17:34:45',
        "fecha_final" => "",
        "demanda_laboral" => "falta una cajera",
        "objetivo" => "conseguir personal especificamente para la caja",
        "lugarid" => 2,
    ],
    "oferta3" => [
        "id" => 3,
        "ambiente_trabajoid" => 1,
        "nombre_sucursal" => 'Sucursal Nº 2',
        "puesto" => "Limipieza",
        "area" => "",
        "fecha_inicial" => '2018-09-13 09:34:45',
        "fecha_final" => "",
        "demanda_laboral" => "falta mantenimiento en la sucursal",
        "objetivo" => "conseguir personal especificamente para limpieza",
        "lugarid" => 2,
    ],
    "oferta4" => [
        "id" => 4,
        "ambiente_trabajoid" => 2,
        "nombre_sucursal" => 'Sucursal Nº 1',
        "puesto" => "Limipieza",
        "area" => "",
        "fecha_inicial" => '2019-06-16 16:03:49',
        "fecha_final" => "2019-09-12 16:03:49",
        "demanda_laboral" => "falta mantenimiento en la sucursal",
        "objetivo" => "conseguir personal especificamente para limpieza",
        "lugarid" => 3,
    ],
    "oferta5" => [
        "ambiente_trabajoid" => 2,
        "nombre_sucursal" => 'Sucursal Nº 1',
        "puesto" => "Limipieza",
        "area" => "",
        "fecha_inicial" => '2019-11-15 16:25:45',
        "fecha_final" => "",
        "demanda_laboral" => "falta mantenimiento en la sucursal",
        "objetivo" => "conseguir personal especificamente para limpieza",
        "lugarid" => 3,
    ],
    
    
];
